"""add validation note

Revision ID: 6621505188b5
Revises: 6e08fc62212b
Create Date: 2026-03-02 19:49:20.037205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6621505188b5'
down_revision: Union[str, None] = '6e08fc62212b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('validation_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'validation_note')
    # ### end Alembic commands ###
