"""add incident validation fields

Revision ID: 6e08fc62212b
Revises: 
Create Date: 2026-03-02 18:48:46.611372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e08fc62212b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('validated_by', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('validated_at', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'users', ['validated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'rejection_reason')
    op.drop_column('incidents', 'validated_at')
    op.drop_column('incidents', 'validated_by')
    # ### end Alembic commands ###
